LIBFT_PATH = libft

NAME = server
NAME_CLIENT = client

NAME_BONUS= server_bonus
NAME_CLIENT_BONUS = client_bonus

SCRS_SERVER = main_s.c
OBJS_SERVER = $(SCRS_SERVER:.c=.o)

SCRS_CLIENT = main_c.c
OBJS_CLIENT = $(SCRS_CLIENT:.c=.o)

SCRS_SERVER_BONUS = main_s_bonus.c
OBJS_SERVER_BONUS = $(SCRS_SERVER_BONUS:.c=.o)

SCRS_CLIENT_BONUS = main_c_bonus.c
OBJS_CLIENT_BONUS = $(SCRS_CLIENT_BONUS:.c=.o)

HEADER = minitalk.h

COMPILER = CC
CFLAGS= -Wall -Werror -Wextra
LIBRARY_FLAG = -Llibft -lft -o

RM = rm -rf

all: make-library $(NAME) $(NAME_CLIENT)

make-library:
	$(MAKE) -C $(LIBFT_PATH)

$(NAME): $(OBJS_SERVER) $(HEADER)
	$(COMPILER) $(CFLAGS) $(LIBRARY_FLAG) $(NAME) $(OBJS_SERVER)

$(NAME_CLIENT): $(OBJS_CLIENT) $(HEADER)
	$(COMPILER) $(CFLAGS) $(LIBRARY_FLAG) $(NAME_CLIENT) $(OBJS_CLIENT)

clean:
	$(MAKE) clean -C $(LIBFT_PATH)
	$(RM) $(OBJS_CLIENT) $(OBJS_SERVER) $(OBJS_CLIENT_BONUS) $(OBJS_SERVER_BONUS)

fclean: clean
	$(MAKE) fclean -C $(LIBFT_PATH)
	$(RM) $(NAME) $(NAME_CLIENT) $(NAME_BONUS) $(NAME_CLIENT_BONUS)

re: fclean
	$(MAKE) all

bonus: make-library $(NAME_BONUS) $(NAME_CLIENT_BONUS)
	

$(NAME_BONUS): $(OBJS_SERVER_BONUS) $(HEADER)
	$(COMPILER) $(CFLAGS) $(LIBRARY_FLAG) $(NAME_BONUS) $(OBJS_SERVER_BONUS)

$(NAME_CLIENT_BONUS): $(OBJS_CLIENT_BONUS) $(HEADER)
	$(COMPILER) $(CFLAGS) $(LIBRARY_FLAG) $(NAME_CLIENT_BONUS) $(OBJS_CLIENT_BONUS)


